"""Position and heading from radar wall returns, on synthetic footprints.

The map is a few rectangular buildings around a street; the rig is placed at
a known pose, returns are generated by casting rays at the footprint edges,
and the solver is handed a *wrong* prior. What it must do is find the truth
inside the prior's sigma box, say how sure it is, and — when the walls seen
cannot pin an axis — say that instead of guessing.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import List, Tuple

import pytest

np = pytest.importorskip("numpy")

from mapinit.nav.walls import (  # noqa: E402
    MIN_RETURNS,
    PosePrior,
    WallMatcher,
    WallReturn,
    footprint_edges,
    local_scales,
    returns_to_local,
    static_returns,
)

LAT, LON = 31.7683, 35.2137


@dataclass(frozen=True)
class Box:
    """A building as (longitude, latitude) ring, built from local metres."""

    ring: Tuple[Tuple[float, float], ...]


def box(x0: float, y0: float, x1: float, y1: float) -> Box:
    lon_scale, lat_scale = local_scales(LAT)
    corners = [(x0, y0), (x1, y0), (x1, y1), (x0, y1), (x0, y0)]
    return Box(tuple((LON + x / lon_scale, LAT + y / lat_scale) for x, y in corners))


def street() -> List[Box]:
    """Buildings either side of a north-south street 12 m wide, with side gaps
    at different places on each side and a building closing the street to
    the north - so that every axis is pinned by something within range."""
    return [box(-30, -20, -6, 12), box(-30, 23, -6, 40),          # west: 11 m gap
            box(6, -20, 30, 4), box(6, 8, 30, 40),                 # east: 4 m gap, offset
            box(-30, 42, 30, 56)]                                  # closes the street


def cast_returns(buildings, x: float, y: float, heading_deg: float,
                 azimuths=range(-75, 76, 5), max_range: float = 40.0,
                 noise_m: float = 0.0, seed: int = 0) -> List[WallReturn]:
    """Ray-cast from the true pose at the footprint edges: what a radar sees."""
    rng = np.random.default_rng(seed)
    prior = PosePrior(LAT, LON, heading_deg, 1.0, 1.0)
    segs = footprint_edges(buildings, prior, radius_m=200.0)
    out = []
    for az in azimuths:
        b = math.radians(heading_deg + az)
        dx, dy = math.sin(b), math.cos(b)
        best = None
        for x0, y0, x1, y1 in segs:
            # ray (x,y)+t(dx,dy) vs segment; solve 2x2
            ex, ey = x1 - x0, y1 - y0
            den = dx * ey - dy * ex
            if abs(den) < 1e-9:
                continue
            t = ((x0 - x) * ey - (y0 - y) * ex) / den
            u = ((x0 - x) * dy - (y0 - y) * dx) / den
            if t > 0.5 and 0.0 <= u <= 1.0 and t <= max_range and (best is None or t < best):
                best = t
        if best is not None:
            out.append(WallReturn(best + rng.normal(0.0, noise_m), float(az)))
    return out


def test_recovers_true_pose_from_a_wrong_prior():
    truth = (2.0, 5.0, 12.0)                     # x east, y north, heading
    returns = cast_returns(street(), *truth, noise_m=0.05)
    assert len(returns) >= MIN_RETURNS
    prior = PosePrior(LAT, LON, heading_deg=truth[2] + 6.0, sigma_position_m=3.0,
                      sigma_heading_deg=4.0, source="manual_pin")
    fix = WallMatcher().match(returns, street(), prior)
    lon_scale, lat_scale = local_scales(LAT)
    x = (fix.longitude - LON) * lon_scale
    y = (fix.latitude - LAT) * lat_scale
    assert fix.accepted, str(fix) + "\n" + "\n".join(str(c) for c in fix.checks)
    assert abs(x - truth[0]) < 0.4 and abs(y - truth[1]) < 0.4
    assert abs(fix.heading_deg - truth[2]) < 1.0
    assert fix.inlier_fraction > 0.9
    assert fix.sigma_east_m < 1.0 and fix.sigma_heading_deg < 2.0
    assert not fix.ambiguous and not fix.on_boundary


def test_a_single_straight_wall_is_reported_ambiguous_along_it():
    # One long wall to the east only: range to it pins east and heading, but
    # nothing seen changes when the rig slides north.
    walls = [box(8, -80, 30, 80)]
    returns = cast_returns(walls, 0.0, 0.0, 0.0, azimuths=range(20, 76, 5))
    prior = PosePrior(LAT, LON, 0.0, sigma_position_m=3.0, sigma_heading_deg=3.0)
    fix = WallMatcher().match(returns, walls, prior)
    assert fix.ambiguous and fix.ambiguity_axis == "north"
    assert not fix.accepted
    assert any(c.name == "walls.unambiguous" and not c.passed for c in fix.checks)


def test_too_few_returns_is_a_named_failure_not_a_guess():
    prior = PosePrior(LAT, LON, 0.0, 3.0, 3.0)
    fix = WallMatcher().match([WallReturn(5.0, 0.0)] * 3, street(), prior)
    assert not fix.accepted
    assert fix.dx_m == 0.0 and fix.heading_deg == prior.heading_deg
    assert any(c.name == "walls.returns" and not c.passed for c in fix.checks)


def test_no_map_nearby_is_a_named_failure():
    far = [box(500, 500, 520, 520)]
    returns = [WallReturn(5.0 + i, -30.0 + 10 * i) for i in range(8)]
    fix = WallMatcher().match(returns, far, PosePrior(LAT, LON, 0.0, 3.0, 3.0))
    assert not fix.accepted
    assert any(c.name == "walls.edges_nearby" and not c.passed for c in fix.checks)


def test_a_prior_worse_than_its_sigma_is_flagged_on_the_boundary():
    truth = (0.0, 0.0, 0.0)
    returns = cast_returns(street(), *truth)
    # Claims 1 m, is 2.9 m off: the best pose lands on the edge of the box.
    prior = PosePrior(LAT, LON + 2.9 / local_scales(LAT)[0], 0.0, 1.0, 2.0)
    fix = WallMatcher().match(returns, street(), prior)
    assert fix.on_boundary
    assert not fix.accepted
    assert any(c.name == "walls.inside_search" and not c.passed for c in fix.checks)


def test_frame_convention_positive_azimuth_is_right():
    # Facing north, a return at +90 deg must land east of the rig.
    pts = returns_to_local([WallReturn(10.0, 90.0)], heading_deg=0.0)
    assert pts[0][0] == pytest.approx(10.0) and abs(pts[0][1]) < 1e-9
    # Facing east, +90 deg is south.
    pts = returns_to_local([WallReturn(10.0, 90.0)], heading_deg=90.0)
    assert pts[0][1] == pytest.approx(-10.0, abs=1e-9)


def test_static_returns_filters_like_the_api_records():
    dets = [
        {"range_m": 0.2, "azimuth_deg": 0.0, "is_static": True},        # self-coupling
        {"range_m": 5.0, "azimuth_deg": 10.0, "is_static": True},
        {"range_m": 6.0, "azimuth_deg": -10.0, "velocity_mps": 1.5},    # moving, no flag
        {"range_m": 7.0, "azimuth_deg": 20.0, "velocity_mps": 0.1},     # still, no flag
        {"range_m": 55.0, "azimuth_deg": 0.0, "is_static": True},       # too far
    ]
    got = static_returns(dets)
    assert [(w.range_m, w.azimuth_deg) for w in got] == [(5.0, 10.0), (7.0, 20.0)]


def test_solve_is_fast_enough_for_a_live_tick():
    import time
    returns = cast_returns(street(), 1.0, 1.0, 5.0)
    prior = PosePrior(LAT, LON, 0.0, 3.0, 5.0)
    t0 = time.perf_counter()
    WallMatcher().match(returns, street(), prior)
    assert time.perf_counter() - t0 < 5.0
